Update laraflask_healthcheck.yml

diff --git a/.github/workflows/laraflask_healthcheck.yml b/.github/workflows/laraflask_healthcheck.yml
--- a/.github/workflows/laraflask_healthcheck.yml
+++ b/.github/workflows/laraflask_healthcheck.yml
@@ -1,4 +1,4 @@
-name: Laraflask Health Check
+name: Run pytest
 
 on:
   push:
@@ -26,9 +26,16 @@ jobs:
     - name: Access CONTAINER_IP from GITHUB_ENV
       run: echo "Container IP is $CONTAINER_IP"
 
+    # Curl to /test/health_check and check if the response text is 'OK'
     - name: Curl to /test/health_check 
       run: |
-        curl -s http://$CONTAINER_IP:5000/test/health_check
+        response=$(curl -s http://$CONTAINER_IP:5000/test/health_check)
+        if [ "$response" = "OK" ]; then
+          echo "Health check successful"
+        else
+          echo "Health check failed: $response"
+          exit 1
+        fi
 
     - name: Stop Docker Compose
       run: docker-compose -f docker-compose.dev.yml down
